name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: nix build .#dockerImage

      - name: Load Docker image
        run: docker load < result

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag docker image
        run: |
          docker tag texlive-lualatex ghcr.io/${{ github.repository_owner }}/texlive-lualatex:latest

      - name: Push Docker image to GitHub Container Repo
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/texlive-lualatex:latest
